apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zcn90oygi-python 
  janus-idp.io/tekton: zcn90oygi-python
  backstage.io/kubernetes-id: zcn90oygi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zcn90oygi-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml